---
# tasks file for exporter
- name: create node user 
  user:
    name: node_exporter
    comment: node exporter
    shell: /sbin/nologin
    create_home: no
    home: /

- name: node_exporter
  unarchive:
    src: "{{ exporter_url }}"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
    remote_src: yes

- name: mv bin
  shell:
    chdir: /usr/local/bin
    cmd: "mv {{ exporter_dir }}/node_exporter ./ && rm -rf {{ exporter_dir }}"

- name: copy service file
  copy:
    src: roles/rasp_exporter/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0755

- name: reload service 
  shell:
    cmd: systemctl daemon-reload

- name: start node_exporter
  service:
    name: node_exporter
    state: started
    enabled: yes
