---
# tasks file for exporter
- name: create node user 
  user:
    name: node_exporter
    comment: node exporter
    shell: /sbin/nologin
    create_home: no
    home: /

- name: node_exporter
  unarchive:
    src: "{{ exporter_url }}"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
    remote_src: yes

- name: mv bin
  shell:
    chdir: /usr/local/bin
    cmd: "mv {{ exporter_dir }}/node_exporter ./ && rm -rf {{ exporter_dir }}"

- name: put service file
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0755

- name: reload service 
  shell:
    cmd: systemctl daemon-reload

- name: start node_exporter
  service:
    name: node_exporter
    state: started
    enabled: yes

- block:
  - name: check firewall
    shell: "firewall-cmd --zone=public --list-ports | grep 9100"
    #ignore_errors: yes
    register: firewall_check
    changed_when: no
    failed_when: firewall_check.rc > 1
  - name: update firewall
    shell: "firewall-cmd --permanent --zone=public --add-port=9100/tcp && firewall-cmd --reload"
    when: firewall_check.rc != 0
  when: ansible_os_family == 'RedHat'

